const messages = {
    mn: {
        menu: {
            home: "Нүүр",
            lang: "Language",
            contact: "Холбоо барих",
            fontsize:"Үсгийн хэмжээ",
            standard:"Стандарт",
            zoom :"Томруулах",
            search:"Хайх  ",
            search2:"Хайлтын утга",
// sidebar1
            sb10:"Японд суралцах сонирхол",
            sb11:"Дэвшилтэт технологи, хөгжсөн эдийн засаг",
            sb12:"Сэтгэл татам соёл",
            sb13:"Оршин суухад тохиромжтой амьдрах орчин",
            sb14:"Олон орноос ирэх гадаад оюутнууд",
            sb15:"Японы бүс нутаг бүрийн онцлог",
// sidebar2
            sb20:"Гадаадад суралцах төлөвлөгөө",
            sb21:"Боловсролын систем",
            sb22:"Сургуулиа мэдэх",
            sb23:"Япон хэлний байгууллага",
            sb24:"Мэргэшсэн сургалтын коллеж (мэргэшсэн курс)",
            sb25:"Технологийн коллеж",
            sb26:"Их сургууль (факультет)/Бага коллеж",
            sb27:"Төгсөх ангийн оюутан",

            sb30:"Гадаадад суралцах хэв маяг",
            sb31:"Засгийн газраас ивээн тэтгэдэг гадаад оюутан",
            sb32:"Гадаадад хувийн зардлаар суралцах",
            sb33:"Англи хэлээр заадаг зэрэг олгох хөтөлбөрүүд",
            sb34:"Богино хугацааны хөтөлбөр",
            sb35:"Шилжүүлэх элсэлт",
            sb36:"Гадаадад суралцах схем",
            sb37:"Японд суралцахад ашигладаг янз бүрийн шалгалтууд",
            sb38:"Гадаадад суралцах зардал",
            sb39:"Тэтгэлэг",
            sb3end:"Цагаачлалын журам, оршин суугаа байдлын тухай",
// sidebar3
            sb40:"Япон дахь амьдрал",
            sb41:"Амьжиргааны зардал болон өртөг",
            sb42:"Амьдрах байр сууц",
            sb43:"Даатгал",
            sb44:"Оршин суух зөвшөөрөлтэй холбоотой зүйлс",
            sb45:"Орон нутгийн засаг захиргаанаас өгөх дэмжлэг",
// sidebar4
            sb50:"Япон дахь хямралын менежмент",
            sb51:"Газар хөдлөлт",
            sb52:"Өдөр тутмын бэлтгэл чухал",
            sb53:"Тэр үед би яах ёстой вэ?",
            sb54:"Өдөр тутмын бэлтгэл",
            sb55:"Гамшгийн үед утас ажиллах уу?",
            sb56:"Би хаана нүүлгэн шилжүүлэх ёстой вэ?",
            sb57:"Гамшиг тохиолдоход би юу хийж чадах вэ?",
            sb60:"Гал",
            sb61:"Халаагчийг хэрхэн яаж зохицуулах вэ",
            sb62:"Гал гарсан тохиолдолд",
            sb63:"Осол",
            sb64:"Япон аюулгүй орон мөн үү?",
            sb65:"Энэ бол гэмт хэрэг!",
            sb66:"Унадаг дугуй маш аюултай",
            sb67:"Машин барих",
            sb70:"Анагаах ухаан",
            sb71:"Ханиад хүрэхгүйн тулд",
            sb72:"Өвдөхөд",
            sb73:"Яаралтай байдал (шөнийн цагаар, амралт)",
            sb74:"Даатгалын системийн тухай",
// sidebar5
            sb80:"Японд хөдөлмөр эрхлэх нь",
            sb81:"Цагийн ажил",
            sb82:"Мэргэжлийн дадлага",
            sb83:"Японд ажилд орох",
            sb84:"Хөдөлмөр эрхлэхтэй холбогдуулан оршин суух зөвшөөрлийн ангилал өөрчлөх тухай",

        },
        partTime: {
            head_title: "Цагийн ажил",
            text1: "Хувийн зардлаар сурдаг гадаад оюутнуудын 67% нь цагийн ажил хийдэг бөгөөд сард дунджаар 59,000 иэн (413 ам. доллар)-н цалинтай байдаг. Цагийн ажил хийснээр сургалтын бүх төлбөр, амьжиргааны зардлыг нөхөх боломжгүй тул цагийн ажилд найдахгүйгээр санхүүгийн төлөвлөгөө гаргах хэрэгтэй.",
            frame1_text: "Цагийн ажил хийх тохиолдолд дараах нөхцөлийг заавал баримтлахгүй бол болохгүй.<br />Эдгээрийг зөрчсөн тохиолдолд хуулийн хариуцлага хүлээх, албадан гарах эрсдэлтэй гэдгийг анхаарна уу. Үүнд:",
            frame1_line1: 'Өөрт хамгийн ойр байрших Гадаадын иргэн харьяатын асуудал хариуцсан газарт "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийг мэдүүлэх. "Гадаад оюутан" ангиллын оршин суух зөвшөөрөлтэйгээр 3-аас дээш сар оршин суугаа эсвэл Япон Улсын хилээр анх нэвтрэх үедээ тухайн нисэх буудал дээр "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийг мэдүүлэх боломжтой.',
            frame1_line2: "Хичээл сурлагад нөлөөлөхгүй байх.",
            frame1_line3: "Орлогын зорилго нь Японд суралцах үеийн сургалтын төлбөр, амьдрах зардалд зарцуулах бөгөөд харин ар гэртээ мөнгө илгээх, мөнгөн хуримтлал үүсгэхэд чиглээгүй байх.",
            frame1_line4: "Садар самуун явдалтай холбогдоогүй байх. ※ Хуулинд хориглосон заалттай.",
            frame1_line5: "Долоо хоногт ажиллсан цаг 28-аас хэтрэхгүй байх.",
            frame1_line5_bold: "(Урт хугацааны амралтын үеэр хоногт 8 цаг байх)",
            frame1_line6: "Боловсролын байгууллагад суралцаж байх хугацаанд хийх.",
            big_title: "Хийх ажлаа сонгохдоо анхаарах зүйлс!",
            text2: "Японд суралцах зорилгоосоо хазайхгүй байх. Эрүүл мэндээ хайхралгүйгээр хэт их ажиллахгүй байх",
            title1: "Хичээл сурлагад тань муугаар нөлөөлөөгүй эсэх",
            text3: "Шөнө орой эсвэл урт цагаар ажиллах нь дараагийн өдөрт ямар нэгэн нөлөө үзүүлэхгүй эсэх.",
            title2: "Цалин хөлс, тэдгээрийг олгох арга зам",
            text4: "Өдрөөр олгох, долоо хоног тутам олгох, сараар олгох, бэлнээр олгож байна уу? Банкаар шилжүүлж байна уу?",
            title3: "Хийх ажил нь эрсдэлгүй эсэх",
            text5: "Аюултай эрсдэлтэй ажил биш эсэх. Ажлын байранд гарч болзошгүй гэнэтийн ослын үед хамгаалалт байгаа эсэх. Цагийн ажил танилцуулж өгөх эсэх талаар тухайн сургуулиасаа тодруулна уу.",
            advice_title: "Нэгэн зөвлөгөө",
            advice_text: "Цагийн ажлаас шалтгаалж хичээлийн ирц хангалтгүй гэх мэтээр хичээлээ орхигдуулснаас болж оршин суух зөвшөөрлийн хугацааг сунгаж чадалгүй нутаг буцах гадаад оюутнууд жил бүр гардаг тул та бүхэн энэ талаар сайтар анхаарна уу.",
            table1_title: "Гадаад оюутнуудын түгээмэл ажилладаг цагийн ажлын төрлүүд",
            table1_row0_2: "Ажлын төрөл",
            table1_row0_3: "Ажлын төрөл",
            table1_row1: "Хоол үйлдвэрлэл, үйлчилгээний газар",
            table1_row2: "Борлуулалт, худалдаа",
            table1_row3: "Үйлдвэрийн угсралт",
            table1_row4: "Багшийн туслах/ судалгааны туслах",
            table1_row5: "Гадаад хэлний багш",
            table1_row6: "Хүргэлт",
            table1_row7: "Цэвэрлэгээ",
            table1_row8: "Оффисийн ажил",
            table1_row9: "Аман болон бичгийн орчуулга",
            table2_title: "Цагийн ажлын цалин хөлс",
            table2_row0_1: "Цагийн хөлс",
            table2_row0_2: "Эзлэх хувь",
            table2_row1: "800 иенээс бага",
            table2_row2: "800-аас 1000 иен хүртэлх",
            table2_row3: "1000-аас 1200 иен хүртэлх",
            table2_row4: "1200-аас ,400 иен хүртэлх",
            table2_row5: "1400 иенээс дээш",
            frame2_title1: '"Японд суралцах хугацаанд мөнгө хуримтлуулах боломжтой" гэж онцгойлох Япон сургууль зуучлалын байгууллагаас болгоомжилно уу.',
            frame2_title2: "Сүүлийн жилүүдэд зарим нэгэн Японы сургууль зуучлах байгууллагууд дараах буруу ойлголтыг нийтэд тарааж буй тул болгоомжтай байна уу.",
            frame2_text1: "1 цагт 3000 иен (21 ам. доллар)-н цалин авах боломжтой.",
            frame2_text1_1: "Цагийн ажлын цалин 1000 иен (7 ам. доллар) байдаг.",
            frame2_text2: "Гадаадад сурч байхдаа цагийн ажил хийж сар бүр 200,000-300,000 иен олох боломжтой, сургалтын төлбөр, амьжиргааны зардлаас илүү гарсан мөнгийг гэр лүүгээ илгээх боломжтой.",
            frame2_text2_1: "Боломжгүй. Цагийн ажлын сарын дундаж цалин 59,000 иен(421 ам.доллар) байдаг.",
            frame2_text4: "Эх сурвалж: 2021 оны хувийн зардалаар сурч буй оюутнуудын амьдрах нөхцлийн судалгаа (JASSO)",
            frame2_text5: "1 ам.доллар = 140 иенээр тооцсон",
        },
        internship: {
            head_title: "Ажил мэргэжлийн дадлага буюу интерншип",
            head_text1: "Оюутан суралцах хугацаандаа хувийн хэвшил зэрэгт өөрийн эзэмшсэн мэргэжил, ирээдүйн карьертайгаа холбогдуулан ажлын туршлага хуримтлуулах тогтолцоог интерншип буюу ажил мэргэжлийн дадлага гэдэг. Ажил мэргэжлийн дадлагыг сургалтын хөтөлбөрт тооцон кредит олгодог сургуулиуд бий. Энэ төрлийн хөтөлбөр бий эсэх, кредит цаг тооцогдох эсэх талаар тухайн сургуулиасаа тодруулаарай.",
            head_text2: 'Мөн цалин хөлстэй байх тохиолдолд танд олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл шаардлагатай болно. Долоо хоногт 28 цагаас дээш цаг дадлагад хамрагдах хүсэлтэй бол тухайн дадлагын агуулгыг нотлох баримт бичгийн хамт харьяа Гадаадын иргэн харьяатын асуудал хариуцсан газарт ганцаарчлан "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийн хүсэлт гаргана уу.',
            title1: "Цагийн ажил болон ажил мэргэжлийн дадлагын ялгаатай тал",
            text11_bold: "Цагийн ажил:",
            text11: "Хөдөлмөрийн хүчээ өгөөд түүний хариуд мөнгө авдаг хөдөлмөр эрхлэлт юм.",
            text12_bold: "Ажил мэргэжлийн дадлага:",
            text12: "Ажиллах боломж олгож, ирээдүйн карьерт хэрэг болохуйц ажлын туршлага. Ихэнхдээ цалин хөлсгүй байдаг.",
            title2: "Ажил мэргэжлийн дадлагыг хайх арга",
            text21_bold: "Их, дээд сургуулийн Хөдөлмөр эрхлэлтийн хэлтэс, нэгжид: ",
            text21: "Зарын самбарыг тогтмол шалгаж байх.",
            text22_bold: "Хөдөлмөр эрхлэлтийг дэмжих сайт: ",
            text22: "ажлын төрөл, салбар харгалзахгүйгээр ажил мэргэжлийн дадлагажигчийг шалгаруулж байдаг.",
            text32_bold: "Зөвхөн ажил мэргэжлийн дадлагажигчийг зуучлах байгууллагууд: ",
            text32: "Хүлээн авагч буюу ажил олгогчийн талаар хангалттай мэдээлэлтэй байдаг тул оюутан, компанийн хооронд барагтаа таарахгүй байх тохиолдол бага.",
            title3: "Бусад улсын Их, дээд сургуулийн оюутан Японд ажил мэргэжлийн дадлага хийх тохиолдолд шаардах оршин суух зөвшөөрөл",
            text31: 'Бусад улсын Их, дээд сургуульд суралцагч оюутан тухайн сургуулийн кредит цаг авах сургалтын хөтөлбөрийн нэгэн хэсэг болгож, Японы аж ахуйн нэгж байгууллагатай байгуулсан гэрээ, хэлэлцээрийг үндэслэн ажлын туршлага хуримтлуулахаар Японы хилээр нэвтэрч буй тохиолдолд уг хөтөлбөр нь цалин хөлстэй эсэх, оршин суух хугацаа зэргээс шалтгаалж, тэдний оршин суух зөвшөөрлийн ангилал нь "Тодорхой үйл ажиллагаа", "Соёлын үйл ажиллагаа", "Богино хугацаагаар оршин суух" эдгээрийн аль нэг болдог.',
            frame1_title: "Эдийн засаг аж үйлдвэрийн яамны Даяарчлалыг идэвхижүүлэх ажил мэргэжлийн дадлагажих хөтөлбөр (Гадаадын их, дээд сургуулийн оюутан, төгсөгчдөд зориулсан)",
            frame1_text1: "Эдийн засаг аж үйлдвэрийн яамнаас гадаадын оюутан, залууст зориулсан Японы жижиг дунд, дундаас дээгүүр түвшний аж ахуйн нэгж байгууллагад ажил мэргэжлийн дадлагажих хөтөлбөрийг зохион байгуулдаг.",
            frame1_text2: "Холбоо барих : Эдийн засаг аж үйлдвэрийн яам, Худалдаа эдийн засаг хамтын ажиллагааны газар, Технологи хүний нөөцийн хамтын ажиллагааны хэлтэс",
            frame1_text3: "Утас : (+81)3-3501-1937",
            frame2_title: "Эрүүл мэнд, нийгмийн халамж, хөдөлмөрийн яам Гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төв (Токио, Нагоя, Осака)",
            frame2_text1: "Хөдөлмөр эрхлэлтийн талаарх мэдээлэл, ажилд зөвлөгөө өгөх, лавлагаа өгөх, дадлага хийх хүсэлтийг хүлээн авдаг.",
            frame2_text2: "Холбоо барих :",
            frame2_text3: "Токио:",
            frame2_text4: "Нагоя:",
            frame2_text5: "Осака:",

        }
    },
    en: {
        menu: {
        
            home: "Home",
            lang: "Language",
            contact: "Contact",
            fontsize:"Font size",
            standard:"Standard",
            zoom:"Zoom  ",
            search:"Search",
            search2:"Search value",
// sidebar1
            sb10:"Attractiveness of studying in Japan",
            sb11:"Advanced technology and developed economy",
            sb12:"Attractive culture",
            sb13:"Livable living environment",
            sb14:"Diverse international students",
            sb15:"Japan in numbers",
// sidebar2
            sb20:"Study abroad plan",
            sb21:"Education system",
            sb22:"Know the school",
            sb23:"Japanese language institution",
            sb24:"Specialized training school (specialized course)",
            sb25:"College of technology",
            sb26:"Universities/junior colleges",
            sb27:"Grad student",
            sb30:"Study abroad style",
            sb31:"Government-sponsored study abroad",
            sb32:"Study abroad at private expense",
            sb33:"English-taught degree programs",
            sb34:"Short-term program",
            sb35:"Transfer admission",
            sb36:"Study abroad flowchart",
            sb37:"Various exams used for studying in Japan",
            sb38:"Study abroad expenses",
            sb39:"Scholarship",
            sb3end:"About immigration procedures and status of residence",
// sidebar3
            sb40:"Life in Japan",
            sb41:"Cost of living and cost",
            sb42:"Residential apartment",
            sb43:"Insurance",
            sb44:"Things related to residence permit",
            sb45:"Support from local authorities",
// sidebar4
            sb50:"Crisis management in Japan",   
            sb51:"Earthquake",   
            sb52:"Daily preparation is important", 
            sb53:"What should I do at that moment?",
            sb54:"Daily preparation",  
            sb55:"Will the phone work in case of a disaster?", 
            sb56:"Where should I evacuate?",  
            sb57:"What can I do when disaster strikes?",
            sb60:"Fire",
            sb61:"How to handle heaters",
            sb62:'In case of fire',
            sb63:"Accident",
            sb64:"Is Japan a safe country?",
            sb65:"This is a crime!",
            sb66:"Bicycles are so dangerous",
            sb67:"Driving a car",
            sb70:"Medical",
            sb71:"To avoid catching a cold",
            sb72:"When I get sick",
            sb73:"Emergency (nighttime, holiday)",
            sb74:"About the insurance system",
//sidebar5
            sb80:"Employment in Japan",
            sb81:"Part time",
            sb82:"Professional practice",
            sb83:"Getting a job in Japan",
            sb84:"About changing the category of residence permit in connection with employment",
        },
        partTime: {
            head_title: "Part-time Work",
            text1: "Approximately 67% of privately financed international students in Japan engage in part-time work. The average monthly earnings from such jobs are approximately 59,000 yen (413 USD). Because it will not be possible to cover all school and learning expenses through part-time work alone, students are advised to engage in financial planning that does not rely on such temporary employment alone.",
            frame1_text: "When engaging in part-time work in Japan, you must abide by the conditions stated below. Failure to do so may result in punishment and even deportation.",
            frame1_line1: 'Apply for "permission to engage in activities other than that permitted under the status of residence previously granted" at the nearest immigration services bureau.',
            frame1_line2: "The part-time work does not affect your studies.",
            frame1_line3: "The earned income is meant to supplement your academic cost and necessary expenses and not for saving or for remittance overseas.",
            frame1_line4: "The part-time work engaged in is not in adult entertainment businesses. Note: Prohibited by law.",
            frame1_line5_bold: "Within 28 hours a week",
            frame1_line5: "(up to eight hours a day during the long school holidays)",
            frame1_line6: "The part-time work is done while you retain student status in an educational institution.",
            big_title: "Key points to consider when deciding on part-time work:",
            text2: "Do not get distracted from your purpose--studying in Japan -- or work so hard that you damage your health.",
            title1: "Will this job hinder to your studies?",
            text3: "Will you be affected the following day by working long hours or late at night?",
            title2: "Wages and payment method",
            text4: "Are your wages paid daily, weekly or monthly? Are your wages paid in cash or via bank transfer?",
            title3: "Is the work safe?",
            text5: "Is your working environment safe? Is there insurance against on-the-job accidents? Ask the school to refer you to part-time jobs.",
            advice_title: "Important Point",
            advice_text: "Every year, we see international students who are forced to leave Japan as they cannot extend their period of authorized stay in the country due to their low school-attendance rates because they work part-time and neglect their studies. You have to be very careful not to let this situation happen.",
            table1_title: "Types of part-time job in which international students are employed",
            table1_row0_2: "Category",
            table1_row0_3: "Ratio",
            table1_row1: "Restaurant business",
            table1_row2: "Sales",
            table1_row3: "Factory worker",
            table1_row4: "Teaching or research assistant",
            table1_row5: "Language teacher",
            table1_row6: "Delivery",
            table1_row7: "Cleaning",
            table1_row8: "General administration",
            table1_row9: "Translation/interpreting",
            table2_title: "Hourly Wage for Part-Time Work",
            table2_row0_1: "Hourly Wage",
            table2_row0_2: "Ratio",
            table2_row1: "Less than 800 yen",
            table2_row2: "800 to less than 1,000 yen",
            table2_row3: "1,000 to less than 1,200 yen",
            table2_row4: "1,200 to less than 1,400 yen",
            table2_row5: "More than 1,400 yen",
            frame2_title1: 'Beware of frauds and scams promising high-paying jobs while studying in Japan',
            frame2_title2: "In recent years, some study abroad brokers have been spreading the following misinformation, so please be careful.",
            frame2_text1: '"It is possible to earn 3,000 yen (21USD) per hour working part-time." ',
            frame2_text1_1: "The average hourly wage for such work is approximately 1,000 yen (7USD).",
            frame2_text2: '"With the ability to earn 200,000 to 300,000 yen a month at part-time jobs while studying in Japan, students can pay for school and living expenses and also send money home."',
            frame2_text2_1: "This is not possible. As noted above, the average for such monthly earnings is around 59,000 yen (413USD).",
            frame2_text4: "*Calculated at the exchange rate of 140 yen per 1USD.",
            frame2_text5: "Source: 2021 Lifestyle Survey of Privately Financed International Students (JASSO)",
        },
        internship: {
            head_title: "Internships",
            head_text1: "Internships allow students who have yet to graduate gain experience in positions related to their major or future career by working in companies. Some universities recognize internships as part of the educational curriculum and give academic credit for it. Please inquire directly with your school about the availability of internship programs at the school and the possibility of earning course credit.",
            head_text2: 'If the internship comes with an income, you need to obtain "permission to engage in activity other than that permitted under the status of residence previously granted." If you wish to do an internship that will require you to work more than 28 hours per week, please apply for "permission to engage in activities other than that permitted under the status of residence previously granted." This requires you to submit materials that make clear the nature of the internship to a regional immigration services bureau.',
            title1: "Difference between part-time jobs and internships",
            text11_bold: "Part-time job:",
            text11: "Work in which you are paid money for your labor.",
            text12_bold: "Internship:",
            text12: "Work experience in which you are given a work opportunity that will be useful for your career plans, etc. Internships are often unpaid.",
            title2: "How to find an internship",
            text21_bold: "University career center:",
            text21: "Be sure to check the office's bulletin board regularly.",
            text22_bold: "Job search websites:",
            text22: "Many internships are available in all types of industries.",
            text32_bold: "Dedicated internship agents:",
            text32: "These agents are highly knowledgeable about companies seeking applicants for their internships, so mismatches between students and companies are much less likely.",
            title3: "Status of residence for students enrolled in a university outside of Japan who wish to do an internship in Japan",
            text31: 'When a student from a foreign university comes to Japan for an internship based on a contract or agreement with a Japanese corporation or other such entity, as a part of the universitys credit-earning curriculum, the status of residence will be one of the following, depending on whether or not there is remuneration, and depending on the length of stay: "Designated Activities," "Cultural Activities," or "Temporary Visitor." ',
            frame1_title_bold: "The Ministry of Economics, Trade, and Industry (METI) Japan Internship Program",
            frame1_title: "（only for current students and graduates of foreign universities）",
            frame1_text1: "METI conducts a project to promote internship programs at medium-sized Japanese companies, targeting young people from outside of Japan.",
            frame1_text2: "Inquiries: Technical Cooperation Division, Trade and Economic Cooperation Bureau, METI",
            frame1_text3: "Tel：(+81)3-3501-1937　",
            frame2_title_bold: "Ministry of Health, Labor and Welfare Employment Service Center for Foreigners",
            frame2_title: "（Tokyo・Nagoya・Osaka）",
            frame2_text1: "It provides employment information, job counseling and referrals, and accepts internship applications.",
            frame2_text2: "Inquiries：",
            frame2_text3: "Tokyo:",
            frame2_text4: "Nagoya:",
            frame2_text5: "Osaka:",

        }
    },
    jp: {
        menu: {
            home: "ホームページ",
            lang: "Language",
            contact: "コンタクト",
            fontsize: "フォントサイズ",
            standard:"標準",
            zoom:"ズーム",
            search:"検索",
            search2:"検索値",
//sidebar1
            sb10:"日本留学の魅力",
            sb11:"高度な技術と発展した経済",
            sb12:"魅力的な文化",
            sb13:"住みやすい住環境",
            sb14:"多様な留学生",
            sb15:"数字で見る日本",
// sidebar2
            sb20:"留学プラン",
            sb21:"教育システム",
            sb22:"学校を知る",
            sb23:"日本語教育機関",
            sb24:"専修学校（専門課程）",
            sb25:"高等専門学校",
            sb26:"大学・短期大学",
            sb27:"大学院生",
            sb30:"留学スタイル",
            sb31:"国費留学",
            sb32:"私費留学",
            sb33:"英語で教えられる学位プログラム",
            sb34:"短期プログラム",
            sb35:"転入学",
            sb36:"留学の流れ",
            sb37:"日本留学に必要な各種試験",
            sb38:"留学費用",
            sb39:"奨学金",
            sb3end:"入国手続きと在留資格について",
// sidebar3
            sb40:"日本での生活",
            sb41:"生活費と生活費",
            sb42:"住宅用アパート",
            sb43:"保険",
            sb44:"滞在許可に関すること",
            sb45:"地方自治体からのサポート",
// sidebar4
            sb50:"日本の危機管理",
            sb51:"地震",
            sb52:"日頃の備えが大切",
            sb53:"その時はどうすればいいでしょうか？",
            sb54:"日々の準備",
            sb55:"災害時に電話は通じますか？",
            sb56:"どこに避難すればいいですか？",
            sb57:"災害が起こったとき、私は何ができるでしょうか？",
            sb60:"火",
            sb61:"ヒーターの扱い方",
            sb62:'火災の場合',
            sb63:"事件",
            sb64:"日本は安全な国ですか？",
            sb65:"これは犯罪です！",
            sb66:"自転車はとても危険です",
            sb67:"車を運転する",
            sb70:"医学",
            sb71:"風邪を引かないようにするには",
            sb72:"病気になったとき",
            sb73:"緊急時（夜間・休日）",
            sb74:"保険制度について",
// sidebar5 
            sb80:"日本での就職",
            sb81:"パートタイム",
            sb82:"専門的診療",
            sb83:"日本で就職する",
            sb84:"雇用に伴う在留資格の変更について",
        },
        partTime: {
            head_title: "アルバイト",
            text1: "私費留学生の約67％がアルバイトをしており、１か月あたりの平均給与は約59,000 円（413米ドル）です。アルバイトだけでは、全ての学費や生活費をカバーできませんので、アルバイトに頼らない資金計画をたてましょう。",
            frame1_text: "アルバイトをするときは、次の条件を守らなければなりません。これらを破った場合、処罰されたり、強制的に国外へ退去させられる可能性があります。",
            frame1_line1: '最寄りの地方出入国管理局等で「資格外活動許可」を受けること。「留学」の在留資格で３か月を超える人は、新規に入国する場合、上陸許可時に空港等において資格外活動許可の申請をすることができます。',
            frame1_line2: "勉強の障害にならないこと。",
            frame1_line3: "留学中の学費や必要経費を補う目的であって、貯金や仕送りのためではないこと。",
            frame1_line4: "風俗営業ではないこと。※法令で禁止されています。",
            frame1_line5_bold: "風俗営業ではないこと。※法令で禁止されています。",
            frame1_line5: "（長期休業期間中は１日８時間以内）であること。",
            frame1_line6: "教育機関に在籍している間に行うものであること。",
            big_title: "仕事を決める時のポイント!",
            text2: "留学の目的から外れたり、無理をして健康を損ねたりしないこと。",
            title1: "学業に支障はないか",
            text3: "夜遅くや長時間の仕事で次の日への影響はないか。",
            title2: "賃金、支払い方法",
            text4: "日払い、週払い、月払い、現金支給か銀行振込か。",
            title3: "仕事内容は安全か",
            text5: "危ない仕事でないか、仕事中の事故の保障はどうか。 アルバイトの紹介は、在籍校に聞いてみましょう。",
            advice_title: "ワンポイントアドバイス",
            advice_text: "アルバイトのために学校の出席率が足りなくなるなど、勉強がおろそかになって、在留期間を更新できずに帰国する留学生が毎年出ています。皆さん、十分に気を付けてください。",
            table1_title: "留学生がアルバイトに就くことが多い職種",
            table1_row0_2: "職種",
            table1_row0_3: "割合",
            table1_row1: "飲食業",
            table1_row2: "営業・販売",
            table1_row3: "工場での組立",
            table1_row4: "ティーチングアシスアント・リサーチアシスタント",
            table1_row5: "語学教師",
            table1_row6: "配達",
            table1_row7: "清掃",
            table1_row8: "一般事務",
            table1_row9: "翻訳・通訳",
            table2_title: "アルバイトの時給!",
            table2_row0_1: "時給",
            table2_row0_2: "割合",
            table2_row1: "800円未満",
            table2_row2: "800～1,000円未満",
            table2_row3: "1,000～1,200円未満",
            table2_row4: "1,200～1,400円未満",
            table2_row5: "1,400円以上",
            frame2_title1: '日本留学中にお金が稼げる」と強調する留学あっせん業者には要注意',
            frame2_title2: "近年、一部の留学あっせん業者が次のような誤った情報を流しているので、気を付けてください。",
            frame2_text1: '「１時間に3,000円（21米ドル）の時給がもらえる。」',
            frame2_text1_1: "通常の時給は1,000円（7米ドル）程度です。",
            frame2_text2: '「留学中はアルバイトで月20～30万円稼げるので、学費と生活費がカバーできる上、国に仕送りができる。」',
            frame2_text2_1: "できません。アルバイト代の平均は月59,000円（421米ドル）です。",
            frame2_text4: "１米ドル＝140円で計算",
            frame2_text5: "出典：令和３年度私費外国人留学生生活実態調査（JASSO）",
        },
        internship: {
            head_title: "インターンシップ",
            head_text1: "学生が在学中に企業等において自らの専攻、将来のキャリアに関連した就業体験をする制度のことをインターンシップといいます。教育課程の一環としてインターンシップを単位として認める学校もあります。制度の有無及び単位の認定については、 直接学校に確認してください。",
            head_text2: 'なお、報酬を得る場合は、「資格外活動許可」を受ける必要があります。週28時間を超えるインターンシップを希望する場合は、インターンシップの内容を明らかにする資料とともに、地方出入国在留管理局等に個別に「資格外活動許可」の申請をしてください。',
            title1: "アルバイトとインターンシップの違い",
            text11_bold: "アルバイト：",
            text11: "労働力を提供することでお金を得る就労。",
            text12_bold: "インターンシップ：",
            text12: "就業機会を与えて、将来のキャリアプラン等に役立ててもらうための就業体験。無報酬であることも多いです。",
            title2: "インターンシップを探す方法",
            text21_bold: "大学等の就職担当部署：",
            text21: "掲示板などを頻繁にチェックしましょう。",
            text22_bold: "就職支援サイト：",
            text22: "業種や職種を問わず多くのインターンシップを募集しています。",
            text32_bold: "インターンシップ専門のあっせん業者：",
            text32: "受け入れ企業のことをよく知っているため、学生と企業のミスマッチが起こりにくいです。",
            title3: "日本国外の大学に在籍している学生が、日本でインターンシップをする場合の在留資格",
            text31: '日本国外の大学に在籍する学生が、その大学の単位取得等教育課程の一環として、日本の企業等との契約や取り決めに基づき就業体験をするために入国する場合は、報酬の有無、滞在期間に応じ、在留資格は「特定活動」、「文化活動」、「短期滞在」のいずれかになります。',
            frame1_title: "経済産業省国際化促進インターンシップ事業（海外の大学生・既卒者を対象とする）",
            frame1_text1: "経済産業省では、外国学生等を対象とした日本の中堅・中小企業におけるインターンシップ事業を実施しています。",
            frame1_text2: "問合せ：経済産業省貿易経済協力局技術・人材協力課",
            frame1_text3: "Tel：(+81)3-3501-1937　",
            frame2_title: "厚生労働省 外国人雇用サービスセンター（東京・名古屋・大阪）",
            frame2_text1: "雇用情報の提供、職業相談や紹介、インターンシップの受付を行っています。",
            frame2_text2: "問い合わせ：",
            frame2_text3: "東　京",
            frame2_text4: "名古屋 ",
            frame2_text5: "大　阪",

        }
    }
}

export default messages;