const messages = {
    mn: {
        menu: {
            home: "Нүүр",
            lang: "Language",
            contact: "Холбоо барих",
            fontsize:"Үсгийн хэмжээ",
            standard:"Стандарт",
            zoom :"Томруулах",
            search:"Хайх  ",
            search2:"Хайлтын утга",
// sidebar1
            sb10:"Японд суралцах сонирхол",
            sb11:"Дэвшилтэт технологи, хөгжсөн эдийн засаг",
            sb12:"Сэтгэл татам соёл",
            sb13:"Оршин суухад тохиромжтой амьдрах орчин",
            sb14:"Олон орноос ирэх гадаад оюутнууд",
            sb15:"Японы бүс нутаг бүрийн онцлог",
// sidebar2
            sb20:"Гадаадад суралцах төлөвлөгөө",
            sb21:"Боловсролын систем",
            sb22:"Сургуулиа мэдэх",
            sb23:"Япон хэлний байгууллага",
            sb24:"Мэргэшсэн сургалтын коллеж (мэргэшсэн курс)",
            sb25:"Технологийн коллеж",
            sb26:"Их сургууль (факультет)/Бага коллеж",
            sb27:"Төгсөх ангийн оюутан",

            sb30:"Гадаадад суралцах хэв маяг",
            sb31:"Засгийн газраас ивээн тэтгэдэг гадаад оюутан",
            sb32:"Гадаадад хувийн зардлаар суралцах",
            sb33:"Англи хэлээр заадаг зэрэг олгох хөтөлбөрүүд",
            sb34:"Богино хугацааны хөтөлбөр",
            sb35:"Шилжүүлэх элсэлт",
            sb36:"Гадаадад суралцах схем",
            sb37:"Японд суралцахад ашигладаг янз бүрийн шалгалтууд",
            sb38:"Гадаадад суралцах зардал",
            sb39:"Тэтгэлэг",
            sb3end:"Цагаачлалын журам, оршин суугаа байдлын тухай",
// sidebar3
            sb40:"Япон дахь амьдрал",
            sb41:"Амьжиргааны зардал болон өртөг",
            sb42:"Амьдрах байр сууц",
            sb43:"Даатгал",
            sb44:"Оршин суух зөвшөөрөлтэй холбоотой зүйлс",
            sb45:"Орон нутгийн засаг захиргаанаас өгөх дэмжлэг",
// sidebar4
            sb50:"Япон дахь хямралын менежмент",
            sb51:"Газар хөдлөлт",
            sb52:"Өдөр тутмын бэлтгэл чухал",
            sb53:"Тэр үед би яах ёстой вэ?",
            sb54:"Өдөр тутмын бэлтгэл",
            sb55:"Гамшгийн үед утас ажиллах уу?",
            sb56:"Би хаана нүүлгэн шилжүүлэх ёстой вэ?",
            sb57:"Гамшиг тохиолдоход би юу хийж чадах вэ?",
            sb60:"Гал",
            sb61:"Халаагчийг хэрхэн яаж зохицуулах вэ",
            sb62:"Гал гарсан тохиолдолд",
            sb63:"Осол",
            sb64:"Япон аюулгүй орон мөн үү?",
            sb65:"Энэ бол гэмт хэрэг!",
            sb66:"Унадаг дугуй маш аюултай",
            sb67:"Машин барих",
            sb70:"Анагаах ухаан",
            sb71:"Ханиад хүрэхгүйн тулд",
            sb72:"Өвдөхөд",
            sb73:"Яаралтай байдал (шөнийн цагаар, амралт)",
            sb74:"Даатгалын системийн тухай",
// sidebar5
            sb80:"Японд хөдөлмөр эрхлэх нь",
            sb81:"Цагийн ажил",
            sb82:"Мэргэжлийн дадлага",
            sb83:"Японд ажилд орох",
            sb84:"Хөдөлмөр эрхлэхтэй холбогдуулан оршин суух зөвшөөрлийн ангилал өөрчлөх тухай",

        },
        partTime: {
            head_title: "Цагийн ажил",
            text1: "Хувийн зардлаар сурдаг гадаад оюутнуудын 67% нь цагийн ажил хийдэг бөгөөд сард дунджаар 59,000 иэн (413 ам. доллар)-н цалинтай байдаг. Цагийн ажил хийснээр сургалтын бүх төлбөр, амьжиргааны зардлыг нөхөх боломжгүй тул цагийн ажилд найдахгүйгээр санхүүгийн төлөвлөгөө гаргах хэрэгтэй.",
            frame1_text: "Цагийн ажил хийх тохиолдолд дараах нөхцөлийг заавал баримтлахгүй бол болохгүй.<br />Эдгээрийг зөрчсөн тохиолдолд хуулийн хариуцлага хүлээх, албадан гарах эрсдэлтэй гэдгийг анхаарна уу. Үүнд:",
            frame1_line1: 'Өөрт хамгийн ойр байрших Гадаадын иргэн харьяатын асуудал хариуцсан газарт "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийг мэдүүлэх. "Гадаад оюутан" ангиллын оршин суух зөвшөөрөлтэйгээр 3-аас дээш сар оршин суугаа эсвэл Япон Улсын хилээр анх нэвтрэх үедээ тухайн нисэх буудал дээр "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийг мэдүүлэх боломжтой.',
            frame1_line2: "Хичээл сурлагад нөлөөлөхгүй байх.",
            frame1_line3: "Орлогын зорилго нь Японд суралцах үеийн сургалтын төлбөр, амьдрах зардалд зарцуулах бөгөөд харин ар гэртээ мөнгө илгээх, мөнгөн хуримтлал үүсгэхэд чиглээгүй байх.",
            frame1_line4: "Садар самуун явдалтай холбогдоогүй байх. ※ Хуулинд хориглосон заалттай.",
            frame1_line5: "Долоо хоногт ажиллсан цаг 28-аас хэтрэхгүй байх.",
            frame1_line5_bold: "(Урт хугацааны амралтын үеэр хоногт 8 цаг байх)",
            frame1_line6: "Боловсролын байгууллагад суралцаж байх хугацаанд хийх.",
            big_title: "Хийх ажлаа сонгохдоо анхаарах зүйлс!",
            text2: "Японд суралцах зорилгоосоо хазайхгүй байх. Эрүүл мэндээ хайхралгүйгээр хэт их ажиллахгүй байх",
            title1: "Хичээл сурлагад тань муугаар нөлөөлөөгүй эсэх",
            text3: "Шөнө орой эсвэл урт цагаар ажиллах нь дараагийн өдөрт ямар нэгэн нөлөө үзүүлэхгүй эсэх.",
            title2: "Цалин хөлс, тэдгээрийг олгох арга зам",
            text4: "Өдрөөр олгох, долоо хоног тутам олгох, сараар олгох, бэлнээр олгож байна уу? Банкаар шилжүүлж байна уу?",
            title3: "Хийх ажил нь эрсдэлгүй эсэх",
            text5: "Аюултай эрсдэлтэй ажил биш эсэх. Ажлын байранд гарч болзошгүй гэнэтийн ослын үед хамгаалалт байгаа эсэх. Цагийн ажил танилцуулж өгөх эсэх талаар тухайн сургуулиасаа тодруулна уу.",
            advice_title: "Нэгэн зөвлөгөө",
            advice_text: "Цагийн ажлаас шалтгаалж хичээлийн ирц хангалтгүй гэх мэтээр хичээлээ орхигдуулснаас болж оршин суух зөвшөөрлийн хугацааг сунгаж чадалгүй нутаг буцах гадаад оюутнууд жил бүр гардаг тул та бүхэн энэ талаар сайтар анхаарна уу.",
            table1_title: "Гадаад оюутнуудын түгээмэл ажилладаг цагийн ажлын төрлүүд",
            table1_row0_2: "Ажлын төрөл",
            table1_row0_3: "Ажлын төрөл",
            table1_row1: "Хоол үйлдвэрлэл, үйлчилгээний газар",
            table1_row2: "Борлуулалт, худалдаа",
            table1_row3: "Үйлдвэрийн угсралт",
            table1_row4: "Багшийн туслах/ судалгааны туслах",
            table1_row5: "Гадаад хэлний багш",
            table1_row6: "Хүргэлт",
            table1_row7: "Цэвэрлэгээ",
            table1_row8: "Оффисийн ажил",
            table1_row9: "Аман болон бичгийн орчуулга",
            table2_title: "Цагийн ажлын цалин хөлс",
            table2_row0_1: "Цагийн хөлс",
            table2_row0_2: "Эзлэх хувь",
            table2_row1: "800 иенээс бага",
            table2_row2: "800-аас 1000 иен хүртэлх",
            table2_row3: "1000-аас 1200 иен хүртэлх",
            table2_row4: "1200-аас ,400 иен хүртэлх",
            table2_row5: "1400 иенээс дээш",
            frame2_title1: '"Японд суралцах хугацаанд мөнгө хуримтлуулах боломжтой" гэж онцгойлох Япон сургууль зуучлалын байгууллагаас болгоомжилно уу.',
            frame2_title2: "Сүүлийн жилүүдэд зарим нэгэн Японы сургууль зуучлах байгууллагууд дараах буруу ойлголтыг нийтэд тарааж буй тул болгоомжтай байна уу.",
            frame2_text1: "1 цагт 3000 иен (21 ам. доллар)-н цалин авах боломжтой.",
            frame2_text1_1: "Цагийн ажлын цалин 1000 иен (7 ам. доллар) байдаг.",
            frame2_text2: "Гадаадад сурч байхдаа цагийн ажил хийж сар бүр 200,000-300,000 иен олох боломжтой, сургалтын төлбөр, амьжиргааны зардлаас илүү гарсан мөнгийг гэр лүүгээ илгээх боломжтой.",
            frame2_text2_1: "Боломжгүй. Цагийн ажлын сарын дундаж цалин 59,000 иен(421 ам.доллар) байдаг.",
            frame2_text4: "Эх сурвалж: 2021 оны хувийн зардалаар сурч буй оюутнуудын амьдрах нөхцлийн судалгаа (JASSO)",
            frame2_text5: "1 ам.доллар = 140 иенээр тооцсон",
        },
        internship: {
            head_title: "Ажил мэргэжлийн дадлага буюу интерншип",
            head_text1: "Оюутан суралцах хугацаандаа хувийн хэвшил зэрэгт өөрийн эзэмшсэн мэргэжил, ирээдүйн карьертайгаа холбогдуулан ажлын туршлага хуримтлуулах тогтолцоог интерншип буюу ажил мэргэжлийн дадлага гэдэг. Ажил мэргэжлийн дадлагыг сургалтын хөтөлбөрт тооцон кредит олгодог сургуулиуд бий. Энэ төрлийн хөтөлбөр бий эсэх, кредит цаг тооцогдох эсэх талаар тухайн сургуулиасаа тодруулаарай.",
            head_text2: 'Мөн цалин хөлстэй байх тохиолдолд танд олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл шаардлагатай болно. Долоо хоногт 28 цагаас дээш цаг дадлагад хамрагдах хүсэлтэй бол тухайн дадлагын агуулгыг нотлох баримт бичгийн хамт харьяа Гадаадын иргэн харьяатын асуудал хариуцсан газарт ганцаарчлан "Олгогдсон зөвшөөрлийн хүрээнээс гадуурх үйл ажиллагаа эрхлэх зөвшөөрөл"-ийн хүсэлт гаргана уу.',
            title1: "Цагийн ажил болон ажил мэргэжлийн дадлагын ялгаатай тал",
            text11_bold: "Цагийн ажил:",
            text11: "Хөдөлмөрийн хүчээ өгөөд түүний хариуд мөнгө авдаг хөдөлмөр эрхлэлт юм.",
            text12_bold: "Ажил мэргэжлийн дадлага:",
            text12: "Ажиллах боломж олгож, ирээдүйн карьерт хэрэг болохуйц ажлын туршлага. Ихэнхдээ цалин хөлсгүй байдаг.",
            title2: "Ажил мэргэжлийн дадлагыг хайх арга",
            text21_bold: "Их, дээд сургуулийн Хөдөлмөр эрхлэлтийн хэлтэс, нэгжид: ",
            text21: "Зарын самбарыг тогтмол шалгаж байх.",
            text22_bold: "Хөдөлмөр эрхлэлтийг дэмжих сайт: ",
            text22: "ажлын төрөл, салбар харгалзахгүйгээр ажил мэргэжлийн дадлагажигчийг шалгаруулж байдаг.",
            text32_bold: "Зөвхөн ажил мэргэжлийн дадлагажигчийг зуучлах байгууллагууд: ",
            text32: "Хүлээн авагч буюу ажил олгогчийн талаар хангалттай мэдээлэлтэй байдаг тул оюутан, компанийн хооронд барагтаа таарахгүй байх тохиолдол бага.",
            title3: "Бусад улсын Их, дээд сургуулийн оюутан Японд ажил мэргэжлийн дадлага хийх тохиолдолд шаардах оршин суух зөвшөөрөл",
            text31: 'Бусад улсын Их, дээд сургуульд суралцагч оюутан тухайн сургуулийн кредит цаг авах сургалтын хөтөлбөрийн нэгэн хэсэг болгож, Японы аж ахуйн нэгж байгууллагатай байгуулсан гэрээ, хэлэлцээрийг үндэслэн ажлын туршлага хуримтлуулахаар Японы хилээр нэвтэрч буй тохиолдолд уг хөтөлбөр нь цалин хөлстэй эсэх, оршин суух хугацаа зэргээс шалтгаалж, тэдний оршин суух зөвшөөрлийн ангилал нь "Тодорхой үйл ажиллагаа", "Соёлын үйл ажиллагаа", "Богино хугацаагаар оршин суух" эдгээрийн аль нэг болдог.',
            frame1_title: "Эдийн засаг аж үйлдвэрийн яамны Даяарчлалыг идэвхижүүлэх ажил мэргэжлийн дадлагажих хөтөлбөр (Гадаадын их, дээд сургуулийн оюутан, төгсөгчдөд зориулсан)",
            frame1_text1: "Эдийн засаг аж үйлдвэрийн яамнаас гадаадын оюутан, залууст зориулсан Японы жижиг дунд, дундаас дээгүүр түвшний аж ахуйн нэгж байгууллагад ажил мэргэжлийн дадлагажих хөтөлбөрийг зохион байгуулдаг.",
            frame1_text2: "Холбоо барих : Эдийн засаг аж үйлдвэрийн яам, Худалдаа эдийн засаг хамтын ажиллагааны газар, Технологи хүний нөөцийн хамтын ажиллагааны хэлтэс",
            frame1_text3: "Утас : (+81)3-3501-1937",
            frame2_title: "Эрүүл мэнд, нийгмийн халамж, хөдөлмөрийн яам Гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төв (Токио, Нагоя, Осака)",
            frame2_text1: "Хөдөлмөр эрхлэлтийн талаарх мэдээлэл, ажилд зөвлөгөө өгөх, лавлагаа өгөх, дадлага хийх хүсэлтийг хүлээн авдаг.",
            frame2_text2: "Холбоо барих :",
            frame2_text3: "Токио:",
            frame2_text4: "Нагоя:",
            frame2_text5: "Осака:",
        },
        employmentJapan: {
            head_title: "Японд ажилд орох",
            title_line1: "Японд хөдөлмөр эрхлэх тухай",
            title_line2: "Хөдөлмөр эрхлэхэд шаардлагатай мэдээлэл хэрхэн цуглуулах талаар",
            title_line3: "Зөвлөгөө мэдээлэл өгөх байгууллагуудын танилцуулга (Гадаад ажилтанд зориулсан)",
            title_line4: "Ажиллах газар шийдэгдээгүй байх тохиолдолд",
            big_title1: "Японд хөдөлмөр эрхлэх тухай",
            text1: 'Япон Улсад "Улсын харьяалал үл харгалзан шилдэг сайн хүний нөөцийг бүрдүүлэх", "Гадаад хэл, бусад улсын нөхцөл байдлыг ойлгодог хүний нөөцийн хэрэгцээ шаардлага", "Олон төрлийн суурьтай хүний нөөцийг идэвхитэй ажиллуулмаар байна" гэх мэт бодолтой компаниуд олширч гадаад оюутныг ажилд авах нь эрчимтэй нэмэгдэж байна. Гэвч гадаад оюутнуудын хувьд Японд ажилд орно гэдэг тийм хялбар зүйл биш. Ажил хайх үйл явцын талаар хувийн туршлага, хөдөлмөр эрхлэхтэй холбоотой өдөрлөгийн тухай мэдээллийг түгээдэг тул тэдгээр зөвлөмж тайлбартай танилцангаа эртхэн ажил хайн олцгооё.',
            link1: "Бүлэг 1. Япон дахь хөдөлмөр эрхлэлтийн орчны тухай",
            link2: "Бүлэг 2.Японд ажил хайх тухай",
            link3: "Бүлэг 3. Ажил хайх үйл ажиллагааны хуваарь",
            link4: "Бүлэг 4. Японд ажилд ороход өгөх шалгалт",
            link5: "Бүлэг 5. Оршин суух зөвшөөрөл",
            big_title2: "Хөдөлмөр эрхлэхэд шаардлагатай мэдээлэл хэрхэн цуглуулах талаар",
            title2_1: "Хөдөлмөр эрхлэхтэй холбоотой мэдээллийн сэтгүүлийг үр дүнтэй ашиглах",
            text2_1: "Ажил хайх төлөвлөгөөний талаар мэдээллийг дараах гарын авлагатай харьцуулаад үзээрэй.",
            link2_1: "Японд суралцаж буй гадаад оюутнуудад зохиулсан ажил хайх тухай гарын авлага (JASSO)",
            title2_2: "Гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төвийг ашиглах",
            text2_2: "Эрүүл мэнд, нийгмийн халамж, хөдөлмөрийн яам нь Олон улсын өрсөлдөх чадварыг нэмэгдүүлэх үүднээс гадаад оюутны дотоод дахь хөдөлмөр эрхлэлтийг дэмжих хөтөлбөрийг оролцуулаад нарийн мэргэжил, техникийн салбарын хүрээнд гадаад иргэдийн хөдөлмөр эрхлэлтийг нэмэгдүүлэхээр зорьж, Токио, Нагоя, Осака хот дахь Гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төвүүд болон Фүкүока хотын мэргэжил сургалтын төвөөр дамжуулан Японд суралцах гадаад оюутнуудад хөдөлмөр эрхлэлттэй холбоотой төрөл бүрийн мэдээлэл өгөхөөс гадна сургуульд элсэн орсны дараахнаас л хөдөлмөр эрхлэлтийг дэмжих (хөдөлмөр эрхлэлтийн тухай зааварчилгаа), ажил мэргэжлийн дадлагын хөтөлбөрийн мэдээлэл өгөх, ажлын нэгдсэн ярилцлага зохион байгуулах зэрэг үйл ажиллагааг хэрэгжүүлдэг.",
            text_bold: "Гол дэмжлэгүүдийн тухай",
            li1: "Гадаад оюутнуудад зориулсан хөдөлмөр эрхлэх тухай зааварчилгаа",
            li2: "Их, дээд сургуультай хамтын ажиллагаа (Зочлон очиж зааварчилгаа өгөх)",
            li3: "Гадаад оюутнуудын ажил, мэргэжлийн дадлага",
            li4: "Гадаад оюутнуудад зориулсан ажлын нэгдсэн ярилцлага зохион байгуулах",
            li5: "Гадаад оюутнуудад зориулсан ажил хайх зөвлөгөө мэдээлэл, ажлын байр танилцуулах",
            link2_21: "Токио хот дахь гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төв",
            link2_22: "Нагоя хот дахь гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төв",
            link2_23: "Осака хот дахь гадаад иргэдийн хөдөлмөр эрхлэлтийн үйлчилгээний төв",
            link2_24: "Фүкүока хот дахь шинэ төгсөгчдийг дэмжих Хэлөү ворк",
            title2_3: "Интернэт сүлжээг ашиглах",
            text2_31: "Зөвхөн гадаад оюутнуудад зориулсан мэдээллийн сайт гэлтгүй Япон оюутнуудад чиглэсэн мэдээллийн сайтыг ашиглаарай.",
            text2_32: "Сүүлийн жилүүдэд, ажлын байрны саналыг өөрсдийн албан ёсны цахим хуудсанд нийтэлж, цахим шуудангаар санал хүсэлт хүлээн авдаг компаниуд нэмэгдэж байна.",
            title2_4: "Хамтарсан ажлын байр танилцуулах өдөрлөг, семинарт оролцох",
            text2_41: "Олон тооны компани нэг дор цугларч, зохион байгуулах хамтарсан ажлын байр танилцуулга хийх өдөрлөг, тухайн компани зохион байгуулах семинар (Сонголт хийхгүй) зэрэгт идэвхитэй хамрагдаж тухайн байгууллагатай шууд танилцаад үзээрэй.",
            text2_42: "Семинартай холбогдолтой мэдээлэл нь тухайн компаниудын цахим хуудас, хөдөлмөр эрхлэлтийн талаарх цахим хуудас зэрэгт нийтлэгддэг. Мөн хөдөлмөр эрхлэлтийн талаар мэдээлэл түгээх цахим хуудаснуудаас танилцуулах өдөрлөг, семинарын зохион байгуулагдах өдрийн тухай мэдээлэл хайх боломжтой. Нийтлэгдэж буй мэдээлэл тогтмол шинэчлэгдэж байдаг тул ойр ойрхон шалгаж байгаарай.",
            big_title3: "Зөвлөгөө мэдээлэл өгөх байгууллагуудын танилцуулга (Гадаад ажилтанд зориулсан)",
            text3_1: "Хөдөлмөрийн нөхцөл зэрэг хөдөлмөр эрхлэлттэй холбоотой асуудлын хүрээнд, утсаар гадаад хэлээр зөвлөгөө мэдээлэл өгөх боломжтой цонхны үйлчилгээ юм.",
            link3_1: "Эрүүл мэнд, нийгмийн халамж, хөдөлмөрийн яамны цахим хуудас Зөвлөгөө мэдээлэл өгөх байгууллагуудын талаарх жагсаалт",
            big_title4: "Ажиллах газар шийдэгдээгүй байх тохиолдолд",
            text4_1: 'Японы Их, дээд сургууль※1 эсвэл Мэргэжлийн коллеж※2-ийг төгсөх хүртлээ ажиллах газар шийдэгдээгүй байх тохиолдолд "Гадаад оюутан"-аас "Тодорхой үйл ажиллагаа" гэж оршин суух зөвшөөрлийн ангиллыг өөрчлөх боломжтой ба ингэснээр сургууль төгссөнөөс хойш нэг жилийн хугацаанд (Оршин суух хугацаа хагас жил, зарчмын хувьд нэг удаагийн хугацаа сунгалт хийлгэх боломжтой) ажил хайх үйл ажиллагаагаа үргэлжлүүлэх боломжтой. ※3 Дээрхтэй холбоотой дэлгэрэнгүй зохицуулалтыг харьяа Гадаадын иргэний асуудал хариуцсан газарт хандаж тодруулна уу.',
            li4_1: "Богино хугацааны дээд сургууль эсвэл Магистр, докторын сургууль хамаарна. Гэхдээ тусгай оюутан, лекц сонсогч, сэдэвт суралцагч, судлаач оюутанд хамаарахгүй.",
            li4_2: "Мэргэжлийн цол зэрэгтэй байх тохиолдолд хамаарна.",
            li4_3: "Тодорхой шалгуур болзлыг хангасан тохиолдолд төгссөнөөс хойш 2 дахь жилдээ ажил хайх үйл ажиллагааг үргэлжлүүлэх боломжтой.",

        },
        changingStatus: {
            head_title: "Хөдөлмөр эрхлэхтэй холбогдуулан оршин суух зөвшөөрлийн ангилал өөрчлөх тухай",
            big_title1: "Оршин суух зөвшөөрлийн ангилал өөрчлөх тухай",
            text1_1: 'Япон Улсад оршин суух гадаадын иргэд нийт 29 төрлийн оршин суух зөвшөөрлийн дагуу амьдрах ба бүх зөвшөөрөлд батлагдсан хүрээнд үйл ажиллагаа эрхлэхийг зөвшөөрдөг. Оюутан та хөдөлмөр эрхлэх тохиолдолд оршин суух зөвшөөрлийн ангиллаа өөрчлөх шаардлагатай ба "Гадаад оюутан"-ы ангиллаа "Технологи, хүмүүнлэг, олон улсын ажиллагаа" зэрэг хөдөлмөр эрхлэх боломжтой оршин суух ангилалд шилжүүлдэг. Төгсөх хүртэл хаана ажиллахаа шийдээгүй байх тохиолдолд "Гадаад оюутан"-ы ангиллаас "Тусгай үйл ажиллагаа"-гэх ангилалд шилжүүлж, төгссөнөөс хойш 1 жилийн хугацаанд ажилд хайх үйл ажиллагааг үргэлжлүүлэх боломжтой. (Энэ төрлийн оршин суух зөвшөөрлийн хугацаа нь хагас жил байх ба зөвхөн нэг удаа хагас жилийн сунгалт хийхийг зөвшөөрдөг тул төгсөөд хамгийн ихдээ 1 жил болно)',
            big_title2: "Хүсэлт гаргах",
            text2_1: '"Гадаад оюутан" ангиллаас бусад төрлийн хөдөлмөр эрхлэх боломжтой ангилалд шилжүүлэхдээ зарчмын хувьд тухайн гадаад хүн өөрт хамгийн ойр байх орон нутгийн гадаадын иргэний харьяатын асуудал хариуцсан газар эсвэл үйлчилгээний төвд хандах ёстой. Хүлээж авах цагийн тухайд утсаар холбогдож лавлах хэрэгтэй. Тэр үед дараах баримт бичиг шаардлагатай болно.',
            title2_1: "Оршин суух зөвшөөрөл шилжүүлэхэд шаардагдах баримт бичгүүд",
            bold2_1: '"Технологи, хүмүүнлэг, олон улсын үйл ажиллагаа" ангилалд шилжүүлэх тохиолдолд шаардагдах баримт бичиг',
            li1: "Өөрөө бэлдэх баримт бичиг",
            li1_1: "Өөрийн эзэмшиж буй гадаад паспорт (эсвэл Японд ирснийг батлах баримт)",
            li1_2: "Оршин суух үнэмлэх",
            li1_3: "Оршин суух зөвшөөрлийн ангилал өөрчлөх мэдүүлэг : мэдүүлгийн маягтыг цонхны үйлчилгээнээс авах боломжтой",
            li1_4: "Намтар : тогтсон хэлбэр байхгүй чөлөөтэй бичих ・Боловсролын түүх/Ажилласан түүхийг тодорхой бичих",
            li2: "Ажлын газраас авах баримт бичиг",
            li2_1: "Хөдөлмөрийн гэрээний хуулбар : Ажил олгогчоос өгсөн халагдах тушаал эсвэл ажилд авах тухай мэдэгдлийн аль нь ч байж болно. Хийх ажлын агуулга(аль болох дэлгэрэнгүй)・ажиллах хугацаа ・цалин хөлсний хэмжээг тодорхой тусгасан",
            li2_2: "Компаний тухай албан байгууллагын тодорхойлолт : 3-аас дээшгүй сарын хугацаанд олгосон байх. Санхүүгийн тайлан(Санхүүгийн баланс, ашиг алдагдлын тайлан)",
            li2_3: "Компаний танилцуулга : тухайн компаний үйл ажиллагааг танилцуулсан мэдээлэл бүхий танилцуулга гэх мэт",
            li3: "Их, дээд сургуулиас авах баримт бичиг",
            li3_1: "Төгссөн гэрчилгээ (Төгсөх боломжтойг баталсан тодорхойлолт)-ний эх хуулбар",
            title2_2: '"Гадаад оюутан" ангиллаас "(Ажил хайх үйл ажиллагааг үргэлжлүүлэх зорилготой) тусгай үйл ажиллагаа" ангилалд оршин суух зөвшөөрлөө өөрчлөх тохиолдолд',
            li4: "Өөрөө бэлдэх баримт бичиг",
            li4_1: "Оршин суух зөвшөөрлийн ангилал өөрчлөх мэдүүлэг 1 хувь (орон нутгийн гадаадын иргэний харьяатын асуудал хариуцсан газраас маягтыг авах боломжтой)",
            li4_2: "Цээж зураг",
            li4_3: "Гадаад паспорт",
            li4_4: "Оршин суух үнэмлэх эсвэл оршин суух үнэмлэхэд тооцогдох гадаад иргэний бүртгэлийн гэрчилгээ",
            li4_5: "Мэдүүлэгчийн оршин суух хугацаанд гарах зардлаа төлөх санхүүгийн чадамжийг нотлох бичиг",
            li4_6: "Биеийн байцаалтыг батлах бичиг",
            text2_21: 'Дээрхээс гадна "Гадаад оюутан" ангиллын оршин суух зөвшөөрөлтэйгээр оршин суугаа сургуулийн боловсролын тухай хуулийн дагуу Японы Их, дээд сургуулийг төгссөн гадаад оюутан болон Мэргэжил сургалт, үйлдвэрлэлийн коллежийн мэргэжил олгох курс төгсч мэргэжлийн гэрчилгээ авсан гадаад оюутан эсэхээс шалтгаалан бүрдүүлэх баримт бичиг ондоо байна. Дэлгэрэнгүй мэдээллийг Хууль зүйн яамны цахим хуудаснаас танилцана уу.',
            link2_1: "Хууль зүйн яамны цахим хуудас",
            li5: "Холбогдолтой цахим хуудас",
            link5_1: "Хил нэвтрэх, оршин суух зөвшөөрлийн тухай",
            link5_2: "Японд сурах боломжтой оршин суух зөвшөөрлийн тухай",
        }
    },
    en: {
        menu: {
        
            home: "Home",
            lang: "Language",
            contact: "Contact",
            fontsize:"Font size",
            standard:"Standard",
            zoom:"Zoom  ",
            search:"Search",
            search2:"Search value",
// sidebar1
            sb10:"Attractiveness of studying in Japan",
            sb11:"Advanced technology and developed economy",
            sb12:"Attractive culture",
            sb13:"Livable living environment",
            sb14:"Diverse international students",
            sb15:"Japan in numbers",
// sidebar2
            sb20:"Study abroad plan",
            sb21:"Education system",
            sb22:"Know the school",
            sb23:"Japanese language institution",
            sb24:"Specialized training school (specialized course)",
            sb25:"College of technology",
            sb26:"Universities/junior colleges",
            sb27:"Grad student",
            sb30:"Study abroad style",
            sb31:"Government-sponsored study abroad",
            sb32:"Study abroad at private expense",
            sb33:"English-taught degree programs",
            sb34:"Short-term program",
            sb35:"Transfer admission",
            sb36:"Study abroad flowchart",
            sb37:"Various exams used for studying in Japan",
            sb38:"Study abroad expenses",
            sb39:"Scholarship",
            sb3end:"About immigration procedures and status of residence",
// sidebar3
            sb40:"Life in Japan",
            sb41:"Cost of living and cost",
            sb42:"Residential apartment",
            sb43:"Insurance",
            sb44:"Things related to residence permit",
            sb45:"Support from local authorities",
// sidebar4
            sb50:"Crisis management in Japan",   
            sb51:"Earthquake",   
            sb52:"Daily preparation is important", 
            sb53:"What should I do at that moment?",
            sb54:"Daily preparation",  
            sb55:"Will the phone work in case of a disaster?", 
            sb56:"Where should I evacuate?",  
            sb57:"What can I do when disaster strikes?",
            sb60:"Fire",
            sb61:"How to handle heaters",
            sb62:'In case of fire',
            sb63:"Accident",
            sb64:"Is Japan a safe country?",
            sb65:"This is a crime!",
            sb66:"Bicycles are so dangerous",
            sb67:"Driving a car",
            sb70:"Medical",
            sb71:"To avoid catching a cold",
            sb72:"When I get sick",
            sb73:"Emergency (nighttime, holiday)",
            sb74:"About the insurance system",
//sidebar5
            sb80:"Employment in Japan",
            sb81:"Part time",
            sb82:"Professional practice",
            sb83:"Getting a job in Japan",
            sb84:"About changing the category of residence permit in connection with employment",
        },
        partTime: {
            head_title: "Part-time Work",
            text1: "Approximately 67% of privately financed international students in Japan engage in part-time work. The average monthly earnings from such jobs are approximately 59,000 yen (413 USD). Because it will not be possible to cover all school and learning expenses through part-time work alone, students are advised to engage in financial planning that does not rely on such temporary employment alone.",
            frame1_text: "When engaging in part-time work in Japan, you must abide by the conditions stated below. Failure to do so may result in punishment and even deportation.",
            frame1_line1: 'Apply for "permission to engage in activities other than that permitted under the status of residence previously granted" at the nearest immigration services bureau.',
            frame1_line2: "The part-time work does not affect your studies.",
            frame1_line3: "The earned income is meant to supplement your academic cost and necessary expenses and not for saving or for remittance overseas.",
            frame1_line4: "The part-time work engaged in is not in adult entertainment businesses. Note: Prohibited by law.",
            frame1_line5_bold: "Within 28 hours a week",
            frame1_line5: "(up to eight hours a day during the long school holidays)",
            frame1_line6: "The part-time work is done while you retain student status in an educational institution.",
            big_title: "Key points to consider when deciding on part-time work:",
            text2: "Do not get distracted from your purpose--studying in Japan -- or work so hard that you damage your health.",
            title1: "Will this job hinder to your studies?",
            text3: "Will you be affected the following day by working long hours or late at night?",
            title2: "Wages and payment method",
            text4: "Are your wages paid daily, weekly or monthly? Are your wages paid in cash or via bank transfer?",
            title3: "Is the work safe?",
            text5: "Is your working environment safe? Is there insurance against on-the-job accidents? Ask the school to refer you to part-time jobs.",
            advice_title: "Important Point",
            advice_text: "Every year, we see international students who are forced to leave Japan as they cannot extend their period of authorized stay in the country due to their low school-attendance rates because they work part-time and neglect their studies. You have to be very careful not to let this situation happen.",
            table1_title: "Types of part-time job in which international students are employed",
            table1_row0_2: "Category",
            table1_row0_3: "Ratio",
            table1_row1: "Restaurant business",
            table1_row2: "Sales",
            table1_row3: "Factory worker",
            table1_row4: "Teaching or research assistant",
            table1_row5: "Language teacher",
            table1_row6: "Delivery",
            table1_row7: "Cleaning",
            table1_row8: "General administration",
            table1_row9: "Translation/interpreting",
            table2_title: "Hourly Wage for Part-Time Work",
            table2_row0_1: "Hourly Wage",
            table2_row0_2: "Ratio",
            table2_row1: "Less than 800 yen",
            table2_row2: "800 to less than 1,000 yen",
            table2_row3: "1,000 to less than 1,200 yen",
            table2_row4: "1,200 to less than 1,400 yen",
            table2_row5: "More than 1,400 yen",
            frame2_title1: 'Beware of frauds and scams promising high-paying jobs while studying in Japan',
            frame2_title2: "In recent years, some study abroad brokers have been spreading the following misinformation, so please be careful.",
            frame2_text1: '"It is possible to earn 3,000 yen (21USD) per hour working part-time." ',
            frame2_text1_1: "The average hourly wage for such work is approximately 1,000 yen (7USD).",
            frame2_text2: '"With the ability to earn 200,000 to 300,000 yen a month at part-time jobs while studying in Japan, students can pay for school and living expenses and also send money home."',
            frame2_text2_1: "This is not possible. As noted above, the average for such monthly earnings is around 59,000 yen (413USD).",
            frame2_text4: "*Calculated at the exchange rate of 140 yen per 1USD.",
            frame2_text5: "Source: 2021 Lifestyle Survey of Privately Financed International Students (JASSO)",
        },
        internship: {
            head_title: "Internships",
            head_text1: "Internships allow students who have yet to graduate gain experience in positions related to their major or future career by working in companies. Some universities recognize internships as part of the educational curriculum and give academic credit for it. Please inquire directly with your school about the availability of internship programs at the school and the possibility of earning course credit.",
            head_text2: 'If the internship comes with an income, you need to obtain "permission to engage in activity other than that permitted under the status of residence previously granted." If you wish to do an internship that will require you to work more than 28 hours per week, please apply for "permission to engage in activities other than that permitted under the status of residence previously granted." This requires you to submit materials that make clear the nature of the internship to a regional immigration services bureau.',
            title1: "Difference between part-time jobs and internships",
            text11_bold: "Part-time job:",
            text11: "Work in which you are paid money for your labor.",
            text12_bold: "Internship:",
            text12: "Work experience in which you are given a work opportunity that will be useful for your career plans, etc. Internships are often unpaid.",
            title2: "How to find an internship",
            text21_bold: "University career center:",
            text21: "Be sure to check the office's bulletin board regularly.",
            text22_bold: "Job search websites:",
            text22: "Many internships are available in all types of industries.",
            text32_bold: "Dedicated internship agents:",
            text32: "These agents are highly knowledgeable about companies seeking applicants for their internships, so mismatches between students and companies are much less likely.",
            title3: "Status of residence for students enrolled in a university outside of Japan who wish to do an internship in Japan",
            text31: 'When a student from a foreign university comes to Japan for an internship based on a contract or agreement with a Japanese corporation or other such entity, as a part of the universitys credit-earning curriculum, the status of residence will be one of the following, depending on whether or not there is remuneration, and depending on the length of stay: "Designated Activities," "Cultural Activities," or "Temporary Visitor." ',
            frame1_title_bold: "The Ministry of Economics, Trade, and Industry (METI) Japan Internship Program",
            frame1_title: "（only for current students and graduates of foreign universities）",
            frame1_text1: "METI conducts a project to promote internship programs at medium-sized Japanese companies, targeting young people from outside of Japan.",
            frame1_text2: "Inquiries: Technical Cooperation Division, Trade and Economic Cooperation Bureau, METI",
            frame1_text3: "Tel：(+81)3-3501-1937　",
            frame2_title_bold: "Ministry of Health, Labor and Welfare Employment Service Center for Foreigners",
            frame2_title: "（Tokyo・Nagoya・Osaka）",
            frame2_text1: "It provides employment information, job counseling and referrals, and accepts internship applications.",
            frame2_text2: "Inquiries：",
            frame2_text3: "Tokyo:",
            frame2_text4: "Nagoya:",
            frame2_text5: "Osaka:",

        },
        employmentJapan: {
            head_title: "Employment in Japan",
            title_line1: "Employment in Japan",
            title_line2: "Gathering Information about Job Opportunities",
            title_line3: "Consultation Agencies for Foreign Workers",
            title_line4: "What to do if you cannot find a job",
            big_title1: "Employment in Japan",
            text1: '"We would like to hire talented personnel regardless of nationality," "We need personnel who can speak foreign languages and understand foreign situations," "We would like to actively hire personnel with diverse backgrounds." In Japan, there are a growing number of companies that operate in line with these statements, and the hiring of international students is increasing. However, it is not easy for an international student to be hired in Japan. Job hunting experiences and information on job hunting-related events are posted on this website, so use them as a reference to find a job as soon as possible.',
            link1: "Chapter 1. Employment Environment in Japan",
            link2: "Chapter 2. Job Hunting in Japan",
            link3: "Chapter 3. Job Hunting Schedule",
            link4: "Chapter 4. Employment Examinations",
            link5: "Chapter 5. Status of Residence",
            big_title2: "Gathering Information about Job Opportunities",
            title2_1: "Utilize employment information magazines",
            text2_1: "For information regarding the schedule for finding full-time employment, please refer to the following guidebook:",
            link2_1: "Job Hunting Guide for International Students (JASSO)",
            title2_2: "Utilize the Employment Service Center for Foreigners",
            text2_2: "From the viewpoint of enhancing international competitiveness, the Ministry of Health, Labour and Welfare is promoting the employment of international students in the professional and technical fields, including employment support to international students in Japan. Furthermore, the Ministry of Health, Labour and Welfare is providing international students with a variety of job-finding information through the Tokyo, Nagoya, and Osaka Employment Service Center for Foreigners, employment support (career guidance) starting from an early stage after admission, an internship program, and job interview meetings.",
            text_bold: "Main contents of support",
            li1: "Employment guidance for international students",
            li2: "Cooperation with universities (visit guidance)",
            li3: "Internships for international students",
            li4: "Implementation of job interview meetings for international students",
            li5: "Career counseling and job placement for international students",
            link2_21: "Tokyo Employment Service Center for Foreigners",
            link2_22: "Nagoya Employment Service Center for Foreigners",
            link2_23: "Osaka Employment Service Center for Foreigners",
            link2_24: "Fukuoka Hello Work for Supporting New Graduates(Japanese)",
            title2_3: "Utilize the Internet",
            text2_31: "Utilize not only information websites for the employment of international students but also information websites for Japanese students.",
            text2_32: "More and more companies are now posting job openings on their websites and accepting inquiries via email.",
            title2_4: "Participate in job fairs and seminars",
            text2_41: "Many companies hold job fairs and seminars without specific selection at a venue. You will understand the companies by attending such fairs and seminars. Participate in them actively.",
            text2_42: "Seminar information is published on each corporate websites and job information websites. You can also search for information on such fairs and seminars, including the opening days, on each job information website. Information is constantly updated, so check back often.",
            big_title3: "Consultation Agencies for Foreign Workers",
            text3_1: "This is a telephone consultation service for foreign workers to get advice on working conditions, etc.",
            link3_1: "Ministry of Health, Labour and Welfare website（List of consultation organizations）",
            big_title4: "What to do if you cannot find a job",
            text4_1: 'Even if you are unable to find a job before graduation from the Japanese university※1 or professional training college※2, you can still continue to engage in job-seeking activities in Japan for one more year after graduation by changing your status of residence from "Student" to "Designated Activities." The period of stay of "Designated Activities" is six months, and as a rule, only one additional six-month extension is allowed※3. For more information on procedures, please inquire at a regional immigration bureau.',
            li4_1: "Includes junior colleges and graduate schools. However, this does not include preparatory Japanese language program students, audit students, credit-earning students and research students.",
            li4_2: "Limited to those who have acquired a diploma.",
            li4_3: "If you fulfill certain requirements, you may continue looking for a job into your second year after graduation.",

        },
        changingStatus: {
            head_title: "Procedure for Changing Your Status of Residence",
            big_title1: "Procedure for Changing Your Status of Residence",
            text1_1: 'Foreigners reside in Japan under one of 29 status of residence categories, and the activities that they may engage in are determined by their status of residence. If a foreign student plans to work full-time in Japan, the student must change his or her status of residence from Student to one that allows full-time work in Japan, such as Specialist in the Humanities/International Services or Engineer. Even if your job is not decided until graduation, you may continue finding full-time employment for one year by changing your status of residence from Student to Designated Activities. (The status of residence may be granted for six months with a one-time extension for a maximum of one year.)',
            big_title2: "Application Procedure",
            text2_1: 'To change your status of residence from Student to one of the various types of employment, you must generally visit the nearest regional immigration bureau, bureau branch, or branch office in person. We suggest that you call in advance to confirm their opening hours, etc. The documents that you will need to submit include the following:',
            title2_1: "List of documents required for your status change",
            bold2_1: 'Documents to be submitted when changing to Specialist in the Humanities/International Services or Engineer',
            li1: "Documents that you need to prepare",
            li1_1: "passport (or travel document) in your name",
            li1_2: "Residence card",
            li1_3: "Application for Change of Status of Residence: Application forms are available at the counter",
            li1_4: "Resume: in any format, including accurate information on educational background and job types",
            li2: "Documents that you need to obtain from your employer",
            li2_1: "A copy of your employment contract: Letter of resignation from employing company or letter of employment is acceptable. A description of the type of work to be performed (in as much detail as possible), duration of employment, and amount of compensation required",
            li2_2: "Certified copy of the commercial register of the employing company: issued within the last 3 months. Financial reports (balance sheets and income statements)",
            li2_3: "Company brochures: Brochures or other materials that describe the business activities of the employing company",
            li3: "Documents that you need to obtain from your university",
            li3_1: "Original certificate of graduation (or certificate of expected graduation)",
            title2_2: 'When changing your status of residence from Student to Designated Activities (for continuous job hunting)',
            li4: "Documents that you need to prepare",
            li4_1: "Application form for permission for change of status of residence (available at regional immigration bureau)",
            li4_2: "Photograph",
            li4_3: "Passport",
            li4_4: "Your residence card or alien registration certificate that is regarded as equivalent to residence card",
            li4_5: "Document certifying your ability to pay all of your expenses during your stay in Japan",
            li4_6: "Document to authenticate yourself",
            text2_21: 'Necessary documents vary with the foreigner, and depend on whether the foreigner under the status of residence as Student graduated from a university specified by the School Education Act of Japan or obtained a diploma and finished a specialized course of a professional training college. For details, check the website of the Ministry of Justice.',
            link2_1: "Ministry of Justice website",
            li5: "Related Pages",
            link5_1: "Immigration Procedures and Status of Residence Related to Studying Abroad",
            link5_2: "Status of Residence While You Are Staying in Japan",
        }
    },
    jp: {
        menu: {
            home: "ホームページ",
            lang: "Language",
            contact: "コンタクト",
            fontsize: "フォントサイズ",
            standard:"標準",
            zoom:"ズーム",
            search:"検索",
            search2:"検索値",
//sidebar1
            sb10:"日本留学の魅力",
            sb11:"高度な技術と発展した経済",
            sb12:"魅力的な文化",
            sb13:"住みやすい住環境",
            sb14:"多様な留学生",
            sb15:"数字で見る日本",
// sidebar2
            sb20:"留学プラン",
            sb21:"教育システム",
            sb22:"学校を知る",
            sb23:"日本語教育機関",
            sb24:"専修学校（専門課程）",
            sb25:"高等専門学校",
            sb26:"大学・短期大学",
            sb27:"大学院生",
            sb30:"留学スタイル",
            sb31:"国費留学",
            sb32:"私費留学",
            sb33:"英語で教えられる学位プログラム",
            sb34:"短期プログラム",
            sb35:"転入学",
            sb36:"留学の流れ",
            sb37:"日本留学に必要な各種試験",
            sb38:"留学費用",
            sb39:"奨学金",
            sb3end:"入国手続きと在留資格について",
// sidebar3
            sb40:"日本での生活",
            sb41:"生活費と生活費",
            sb42:"住宅用アパート",
            sb43:"保険",
            sb44:"滞在許可に関すること",
            sb45:"地方自治体からのサポート",
// sidebar4
            sb50:"日本の危機管理",
            sb51:"地震",
            sb52:"日頃の備えが大切",
            sb53:"その時はどうすればいいでしょうか？",
            sb54:"日々の準備",
            sb55:"災害時に電話は通じますか？",
            sb56:"どこに避難すればいいですか？",
            sb57:"災害が起こったとき、私は何ができるでしょうか？",
            sb60:"火",
            sb61:"ヒーターの扱い方",
            sb62:'火災の場合',
            sb63:"事件",
            sb64:"日本は安全な国ですか？",
            sb65:"これは犯罪です！",
            sb66:"自転車はとても危険です",
            sb67:"車を運転する",
            sb70:"医学",
            sb71:"風邪を引かないようにするには",
            sb72:"病気になったとき",
            sb73:"緊急時（夜間・休日）",
            sb74:"保険制度について",
// sidebar5 
            sb80:"日本での就職",
            sb81:"パートタイム",
            sb82:"専門的診療",
            sb83:"日本で就職する",
            sb84:"雇用に伴う在留資格の変更について",
        },
        partTime: {
            head_title: "アルバイト",
            text1: "私費留学生の約67％がアルバイトをしており、１か月あたりの平均給与は約59,000 円（413米ドル）です。アルバイトだけでは、全ての学費や生活費をカバーできませんので、アルバイトに頼らない資金計画をたてましょう。",
            frame1_text: "アルバイトをするときは、次の条件を守らなければなりません。これらを破った場合、処罰されたり、強制的に国外へ退去させられる可能性があります。",
            frame1_line1: '最寄りの地方出入国管理局等で「資格外活動許可」を受けること。「留学」の在留資格で３か月を超える人は、新規に入国する場合、上陸許可時に空港等において資格外活動許可の申請をすることができます。',
            frame1_line2: "勉強の障害にならないこと。",
            frame1_line3: "留学中の学費や必要経費を補う目的であって、貯金や仕送りのためではないこと。",
            frame1_line4: "風俗営業ではないこと。※法令で禁止されています。",
            frame1_line5_bold: "風俗営業ではないこと。※法令で禁止されています。",
            frame1_line5: "（長期休業期間中は１日８時間以内）であること。",
            frame1_line6: "教育機関に在籍している間に行うものであること。",
            big_title: "仕事を決める時のポイント!",
            text2: "留学の目的から外れたり、無理をして健康を損ねたりしないこと。",
            title1: "学業に支障はないか",
            text3: "夜遅くや長時間の仕事で次の日への影響はないか。",
            title2: "賃金、支払い方法",
            text4: "日払い、週払い、月払い、現金支給か銀行振込か。",
            title3: "仕事内容は安全か",
            text5: "危ない仕事でないか、仕事中の事故の保障はどうか。 アルバイトの紹介は、在籍校に聞いてみましょう。",
            advice_title: "ワンポイントアドバイス",
            advice_text: "アルバイトのために学校の出席率が足りなくなるなど、勉強がおろそかになって、在留期間を更新できずに帰国する留学生が毎年出ています。皆さん、十分に気を付けてください。",
            table1_title: "留学生がアルバイトに就くことが多い職種",
            table1_row0_2: "職種",
            table1_row0_3: "割合",
            table1_row1: "飲食業",
            table1_row2: "営業・販売",
            table1_row3: "工場での組立",
            table1_row4: "ティーチングアシスアント・リサーチアシスタント",
            table1_row5: "語学教師",
            table1_row6: "配達",
            table1_row7: "清掃",
            table1_row8: "一般事務",
            table1_row9: "翻訳・通訳",
            table2_title: "アルバイトの時給!",
            table2_row0_1: "時給",
            table2_row0_2: "割合",
            table2_row1: "800円未満",
            table2_row2: "800～1,000円未満",
            table2_row3: "1,000～1,200円未満",
            table2_row4: "1,200～1,400円未満",
            table2_row5: "1,400円以上",
            frame2_title1: '日本留学中にお金が稼げる」と強調する留学あっせん業者には要注意',
            frame2_title2: "近年、一部の留学あっせん業者が次のような誤った情報を流しているので、気を付けてください。",
            frame2_text1: '「１時間に3,000円（21米ドル）の時給がもらえる。」',
            frame2_text1_1: "通常の時給は1,000円（7米ドル）程度です。",
            frame2_text2: '「留学中はアルバイトで月20～30万円稼げるので、学費と生活費がカバーできる上、国に仕送りができる。」',
            frame2_text2_1: "できません。アルバイト代の平均は月59,000円（421米ドル）です。",
            frame2_text4: "１米ドル＝140円で計算",
            frame2_text5: "出典：令和３年度私費外国人留学生生活実態調査（JASSO）",
        },
        internship: {
            head_title: "インターンシップ",
            head_text1: "学生が在学中に企業等において自らの専攻、将来のキャリアに関連した就業体験をする制度のことをインターンシップといいます。教育課程の一環としてインターンシップを単位として認める学校もあります。制度の有無及び単位の認定については、 直接学校に確認してください。",
            head_text2: 'なお、報酬を得る場合は、「資格外活動許可」を受ける必要があります。週28時間を超えるインターンシップを希望する場合は、インターンシップの内容を明らかにする資料とともに、地方出入国在留管理局等に個別に「資格外活動許可」の申請をしてください。',
            title1: "アルバイトとインターンシップの違い",
            text11_bold: "アルバイト：",
            text11: "労働力を提供することでお金を得る就労。",
            text12_bold: "インターンシップ：",
            text12: "就業機会を与えて、将来のキャリアプラン等に役立ててもらうための就業体験。無報酬であることも多いです。",
            title2: "インターンシップを探す方法",
            text21_bold: "大学等の就職担当部署：",
            text21: "掲示板などを頻繁にチェックしましょう。",
            text22_bold: "就職支援サイト：",
            text22: "業種や職種を問わず多くのインターンシップを募集しています。",
            text32_bold: "インターンシップ専門のあっせん業者：",
            text32: "受け入れ企業のことをよく知っているため、学生と企業のミスマッチが起こりにくいです。",
            title3: "日本国外の大学に在籍している学生が、日本でインターンシップをする場合の在留資格",
            text31: '日本国外の大学に在籍する学生が、その大学の単位取得等教育課程の一環として、日本の企業等との契約や取り決めに基づき就業体験をするために入国する場合は、報酬の有無、滞在期間に応じ、在留資格は「特定活動」、「文化活動」、「短期滞在」のいずれかになります。',
            frame1_title: "経済産業省国際化促進インターンシップ事業（海外の大学生・既卒者を対象とする）",
            frame1_text1: "経済産業省では、外国学生等を対象とした日本の中堅・中小企業におけるインターンシップ事業を実施しています。",
            frame1_text2: "問合せ：経済産業省貿易経済協力局技術・人材協力課",
            frame1_text3: "Tel：(+81)3-3501-1937　",
            frame2_title: "厚生労働省 外国人雇用サービスセンター（東京・名古屋・大阪）",
            frame2_text1: "雇用情報の提供、職業相談や紹介、インターンシップの受付を行っています。",
            frame2_text2: "問い合わせ：",
            frame2_text3: "東　京",
            frame2_text4: "名古屋 ",
            frame2_text5: "大　阪",

        },
        employmentJapan: {
            head_title: "留学後の就職",
            title_line1: "日本での就職について",
            title_line2: "就職のための情報の集め方",
            title_line3: "相談機関のご紹介（外国人労働向け）",
            title_line4: "就職が決まらなかった場合",
            big_title1: "日本での就職について",
            text1: '日本では、「国籍を問わず優秀な人材を確保したい」、「外国語や外国の状況を理解している人材が必要」、「多様な背景を持つ人材を積極的に採用したい」と考える企業が増え、外国人留学生の採用は増加しています。しかし、留学生の日本国内での就職は簡単ではありません。就職活動の体験談や就職関連イベント情報を掲載しているので、それらを参考にしながら早めに就職活動をしましょう。',
            link1: "Chapter1．日本の雇用環境について",
            link2: "Chapter2．日本の就職活動",
            link3: "Chapter3．就職活動のスケジュール",
            link4: "Chapter4．日本の就職試験",
            link5: "Chapter5．在留資格",
            big_title2: "就職のための情報の集め方",
            title2_1: "就職情報誌の活用",
            text2_1: "就職活動スケジュールに関する情報については、次のガイドを参照してください。",
            link2_1: "外国人留学生のための就活ガイド（JASSO）",
            title2_2: "外国人雇用サービスセンターの利用",
            text2_2: "厚生労働省では、国際競争力強化の観点から、留学生の国内就職支援も含め、専門的・技術的分野の外国人の就業を促進しており、東京、名古屋、大阪外国人雇用サービスセンターと福岡学生職業センターを拠点に、外国人留学生に対し就職に向けた各種情報を提供するとともに、入学後の早い段階からの就職支援（就職ガイダンス）、インターンシッププログラムの提供、就職面接会等を実施しています。",
            text_bold: "主な支援内容",
            li1: "留学生向け就職ガイダンス",
            li2: "大学との協力（訪問ガイダンス）",
            li3: "留学生インターンシップ",
            li4: "留学生対象就職面接会の実施",
            li5: "留学生に対する職業相談・職業紹介",
            link2_21: "東京外国人雇用サービスセンター",
            link2_22: "名古屋外国人雇用サービスセンター",
            link2_23: "大阪外国人雇用サービスセンター",
            link2_24: "福岡新卒応援ハローワーク",
            title2_3: "インターネットの利用",
            text2_31: "留学生のための情報サイトのみではなく、日本人学生向けの情報サイトも利用しましょう。",
            text2_32: "最近では、求人情報を自社のホームページで公開し、電子メールで問い合わせを受け付ける企業も増えてきています。",
            title2_4: "合同企業説明会・セミナーへの参加",
            text2_41: "たくさんの企業が一つの会場に集まって開催される合同企業説明会や企業が主催するセミナー（選考を伴わないもの）へ積極的に参加し、企業を直接体験してみましょう。",
            text2_42: "セミナーの情報は各企業サイトや就職情報サイトなどに公開されます。 また、各就職情報サイトで説明会・セミナーの開催日等の検索ができます。 情報は常に更新されるため､こまめにチェックしましょう。",
            big_title3: "相談機関のご紹介（外国人労働者向け）",
            text3_1: "労働条件等について、外国語で電話相談できる窓口です。",
            link3_1: "厚生労働省ホームページ　相談機関の窓口一覧",
            big_title4: "就職が決まらなかった場合",
            text4_1: '日本の大学※1または専門学校※2の卒業までに就職が決まらなかった場合でも、「留学」から「特定活動」へ在留資格の変更手続を行うことによって、就職活動を学校卒業後に1年間（在留期間は6ヵ月間、原則として一度の更新が可能）継続して行うことができます※３。手続方法等詳細については、地方入国管理局等に問い合わせましょう。',
            li4_1: "短期大学及び大学院を含む。ただし、別科生、聴講生、科目履修生及び研究生は含まない。",
            li4_2: "専門士の称号を取得したものに限る。",
            li4_3: "一定の要件を満たせば、学校卒業後２年目も継続して就職活動を行うことが可能。.",

        },
        changingStatus: {
            head_title: "就労に関する在留資格の変更手続き",
            big_title1: "在留資格の変更手続き",
            text1_1: '日本に在留する外国人は、全部で29種類ある在留資格の決定を受けて日本に滞在し、各在留資格ごとに定められた範囲でのみ活動を行うことができます。留学生であるあなたが日本において就職する場合には、現在の「留学」の在留資格を「技術・人文知識・国際業務」等就労可能な在留資格に変更することが必要となります。卒業までに就職が決まらなかった場合でも､「留学」から「特定活動」へ在留資格の変更手続きを行うことによって､大学卒業後に就職活動を1年間､継続して行うことができます。 （この在留資格は6ヶ月で､一度だけ更新が認められるため､卒業から最長1年となります。）',
            big_title2: "申請の手続き",
            text2_1: '留学」から各種の就労に在留資格を変更をするための手続は、原則として本人が最寄りの地方出入国在留管理局あるいは支局、出張所に出向いて行ってください。受付時間等については電話で確認するとよいでしょう。その際、提出すべき書類には以下のようなものがあります。',
            title2_1: "在留資格の変更ために必要な書類リスト",
            bold2_1: '技術・人文知識・国際業務」へ変更する場合の提出書類',
            li1: "自分で用意するもの",
            li1_1: "本人名義の旅券（または渡航証明書）",
            li1_2: "在留カード",
            li1_3: "在留資格変更許可申請書：申請用紙は窓口でもらえます",
            li1_4: "履歴書：形式は自由・学歴/職種について正確に記入",
            li2: "就職先からもらうもの",
            li2_1: "雇用契約書のコピー：雇用企業からの辞令や採用通知書でも構わない 従事する職種の内容（できるだけ詳しく）・雇用期間・報酬額の明記必要",
            li2_2: "雇用企業の商業法人登記簿謄本：3ヶ月以内に発行されたもの。決算報告書（貸借対照表・損益計算書）",
            li2_3: "会社案内：雇用企業の事業内容が載っているパンフレット等",
            li3: "大学からもらうもの",
            li3_1: "卒業証明書（卒業見込証明書）の原本",
            title2_2: '「留学」から「（継続就職活動の為の）特定活動」へ在留資格の変更手続きを行う場合',
            li4: "自分で用意するもの",
            li4_1: "在留資格変更許可申請　1通（地方入国管理官署において用紙用意）",
            li4_2: "写真",
            li4_3: "パスポート",
            li4_4: "Y在留カード又は在留カードとみなされる外国人登録証明書",
            li4_5: "申請人の在留中の一切の経費の支弁能力を証する文章",
            li4_6: "身分を証する文章等",
            text2_21: 'その他在留資格「留学」をもって在留する本邦の学校教育法上の大学を卒業した外国人か専修学校専門課程において専門士の称号を取得し卒業した外国人かによって必要な書類が違います。 詳しくは法務省ホームページで確認しましょう。',
            link2_1: "法務省ホームページ",
            li5: "関連ページ",
            link5_1: "入国手続き・在留資格について",
            link5_2: "日本に留学中の在留資格について",
        }
    }
}

export default messages;